version: '3'
services:
  activemq:
    build: activemq
    ports: [ 1883, 5445, 5672, 8161, 61613, 61616 ]
    depends_on: []
    environment:
      - ARTEMIS_USERNAME=guest
      - ARTEMIS_PASSWORD=guest
#       - ARTEMIS_MIN_MEMORY=256M
#       - ARTEMIS_MAX_MEMORY=300M
#
  rabbit:
    image: rabbitmq:3.7.3-management
    ports: [ 5672, 15672 ]
    environment: []
    volumes:
      - "./rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro"
      - "./rabbit/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"

  client:
    build: py-qpid-proton
    entrypoint: ["python", "-u", "helloworld_blocking.py"]
    working_dir: "/usr/local/src/"
    volumes:
      - "./py-qpid-proton/:/usr/local/src/:ro"
    depends_on: 
      - activemq
      - rabbit
    environment:
      AMQP_HOST: "rabbit:5672"
      AMQP_USER: guest123
      AMQP_PASS: admin-1234
