version: '3'
services:
  activemq:
    image: vromero/activemq-artemis:2.2.0
    ports: [ 1883, 5445, 5672, 8161, 61613, 61616 ]
    depends_on: []
    environment:
      - ARTEMIS_USERNAME=username
      - ARTEMIS_PASSWORD=otherpassword
#       - ARTEMIS_MIN_MEMORY=256M
#       - ARTEMIS_MAX_MEMORY=300M
#
  client:
    build: py-qpid-proton
    depends_on: 
      - activemq
    environment:
      AMQP_HOST: "activemq:5672"
      AMQP_USER: username
      AMQP_PASS: otherpassword
